id: P009264
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:38.335311
source_metadata:
  id: bdr:W2PD19980
  title: རྒྱུད་སྡེ་བཞིའི་སྦྱིན་བསྲེག་གི་ཆོ་ག
  author: ''
  volumes:
    6967a1369110471b874a75ec1433b2ee:
      image_group_id: I2PD19989
      title: ''
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
