id: I76928E38
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:07:40+00:00'
last_modified: '2022-06-08T09:47:06.951729+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19980
  title: རྒྱུད་སྡེ་བཞིའི་སྦྱིན་བསྲེག་གི་ཆོ་ག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DDCB:
      image_group_id: I2PD19989
      title: ''
      total_pages: 142
      order: 1
      base_file: DDCB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
